# A Heat environment file which can be used to enable a
# a Cinder NetApp backend, configured via puppet
resource_registry:
  OS::TripleO::Services::CinderBackendNetApp: /usr/share/openstack-tripleo-heat-templates/puppet/services/cinder-backend-netapp.yaml

parameter_defaults:
  CinderEnableIscsiBackend: false
  CinderEnableNetappBackend: true
  CinderNetappBackendName: 'tripleo_netapp'
  CinderNetappLogin: 'vsadmin'
  CinderNetappPassword: 'P@ssw0rd714'
  CinderNetappServerHostname: 'gtsopenstack.openstack.clouda.id'
  CinderNetappServerPort: '443'
  CinderNetappSizeMultiplier: '1.2'
  CinderNetappStorageFamily: 'ontap_cluster'
  CinderNetappStorageProtocol: 'fc'
  CinderNetappTransportType: 'https'
  CinderNetappVfiler: ''
  CinderNetappVolumeList: ''
  CinderNetappVserver: 'GTSOPENSTACK'
  CinderNetappPartnerBackendName: ''
  CinderNetappNfsShares: ''
  CinderNetappNfsSharesConfig: '/etc/cinder/shares.conf'
  CinderNetappNfsMountOptions: ''
  CinderNetappCopyOffloadToolPath: ''
  CinderNetappControllerIps: ''
  CinderNetappSaPassword: ''
  CinderNetappStoragePools: ''
  CinderNetappHostType: ''
  CinderNetappWebservicePath: '/devmgr/v2'
