parameter_defaults:
   ManilaNetappLogin: 'vsadmin'
   ManilaNetappPassword: 'P@ssw0rd'
   ManilaNetappServerHostname: '10.1.118.120'
   ManilaNetappVserver: 'vsadmin'
   ManilaNetappTraceFlags: 'method,api'
   ManilaNetappDriverHandlesShareServers: 'false'